name: Build & release [BETA]

on:
  push:
    tags:
      - "v*"
      - '*-beta.[0-9]+'

env:
  BRANCH_NAME: ${{ github.ref }} 

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-11, ubuntu-20.04, windows-latest]

    steps:
      - name: Exit if not on beta branch
        if: contains(env.BRANCH_NAME, 'beta') == false
        run: | 
          echo "Wrong environment ${{env.BRANCH_NAME}}"
          exit 0

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm i
        
      - name: "Build"
        run: npm run build

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*.AppImage,build/*.yml,build/*.deb,build/*.dmg,build/*.blockmap,build/*.zip,build/*.exe"
          allowUpdates: true
          draft: true
          generateReleaseNotes: true
