name: Create artifact [LINUX ARM64]

on: 
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with: 
          ref: master

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm i
        
      - name: "Build"
        run: npm run build -- --arm64 --linux deb AppImage

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          retention-days: 3
          path: |
            build
            !build/*-unpacked
            !build/.icon-ico
