name: Create artifact [linux]

on: 
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: npm install & build
        run: |
          npm install
          npm run build:local

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          retention-days: 3
          path: |
            build
            !build/linux-unpacked
            !build/.icon-ico
